### ISSUE TITLE
Consider creating Hathi Trust moment

### ISSUE THREAD

**Issue by emulatingkat** [kennethsn/react-stories-api#40]
For some authors such as [https://www.wikidata.org/wiki/Q4678392](url) we know of a copy of their book in Hathi Trust: [https://catalog.hathitrust.org/Record/000019745](url). We may want to display the book in a dedicated moment.

**Comment by kennethsn** [comment]
After investigation, we can leverage the iFrame moment and use HathiTrust embedding server-side so that no change is needed to support this moment type in the UI Components.  🎉
